### ISSUE TITLE
error when use getProxy()

### ISSUE THREAD

**Issue by virbo** [Esyst/PHP-Soap#1]
Helloo, thanks in advance for the extension of his ..
what causes it when I use the method getProxy () appears error Class 'NusoapClient' not found.
how to handle it??
sorry, my english is bad

**Comment by gerben-van-eck** [comment]
Hello,
I forked this repository because I needed it for a project I was working on, and it had some bugs that I needed to fix to make it work.
Eventually I stopped using this library, because it is huge, uses a lot of memory, and is very slow, and this is not easy to solve. NuSoap is very old, if I remember correctly from 2001, and for example includes it's own XML parser where modern PHP can do this by itself using a C library which is inherently much faster than PHP.
I replaced it by a Quick n Dirty self-written library. You basically create a valid SOAP request using for example SoapUI, paste that in either a view or in a text file and using your view library or a PHP str_replace to fill the fields you need, this is only dependent of SimpleXML which is present in most PHP installations by default.
https://gist.github.com/gerben-van-eck/b23ebe298b8719706f28c561fb054c38

That being said, if you get a Class 'blah' not found, the first thing to check would be if you include that file using either autoload or a require statement.
